// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fejztothyxvynyiohoae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZlanp0b3RoeXh2eW55aW9ob2FlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMzc2NTgsImV4cCI6MjA2MjkxMzY1OH0.BkobottFyShCqyGWiMeWhAEcFqVTVGG42W-A4bQeHuM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);